import type { CommandPlatformSnapshot } from "@/types/command-platform";

// Fallback snapshot — used only when /command-platform/bootstrap is
// unreachable.  The dataset mirrors a representative slice of the
// Tomorrow Systems Carrefours master (https://carfmap.replit.app)
// covering Casablanca tram T3/T4, BHNS L5/L6, Fès and El Jadida.
export const fallbackCommandPlatformSnapshot: CommandPlatformSnapshot = {
  cityCenter: {
    lat: 33.585,
    lng: -7.62,
  },
  metrics: {
    throughputVph: 2640,
    delayIndex: 1.14,
    activeControllers: 8,
    incidentsCount: 0,
    updatedAt: "2026-04-27T08:30:00.000Z",
    activeScenario: "peak_traffic",
    city: "Réseau Tomorrow Systems — Maroc",
  },
  intersections: [
    {
      id: "CAR-0147",
      name: "Bd MED 6 / Bd Abbasside",
      district: "Casablanca",
      address: "Bd Mohammed VI × Bd Abbasside",
      location: { lat: 33.576379, lng: -7.599331 },
      mode: "adaptive",
      status: "watch",
      queueLength: 28,
      incidents: 0,
      averageDelaySeconds: 42,
      controllerId: "CTRL-0147",
      controllerConnectionState: "online",
      systemMode: "real",
      lastHeartbeat: "2026-04-27T08:29:45.000Z",
    },
    {
      id: "CAR-0169",
      name: "Rahal Meskini / Abou bakr Essedik",
      district: "Casablanca",
      address: "Rahal Meskini × Abou Bakr Essedik",
      location: { lat: 33.5874771, lng: -7.6158248 },
      mode: "adaptive",
      status: "watch",
      queueLength: 31,
      incidents: 0,
      averageDelaySeconds: 47,
      controllerId: "CTRL-0169",
      controllerConnectionState: "online",
      systemMode: "real",
      lastHeartbeat: "2026-04-27T08:29:30.000Z",
    },
    {
      id: "CAR-0137",
      name: "Bd Moulay Abderrahman / Accès ONCF",
      district: "Casablanca",
      address: "Bd Moulay Abderrahman × Accès ONCF",
      location: { lat: 33.5974227, lng: -7.6110049 },
      mode: "adaptive",
      status: "healthy",
      queueLength: 17,
      incidents: 0,
      averageDelaySeconds: 28,
      controllerId: "CTRL-0137",
      controllerConnectionState: "online",
      systemMode: "real",
      lastHeartbeat: "2026-04-27T08:29:50.000Z",
    },
    {
      id: "CAR-0226",
      name: "Bd Mohammed VI / Bd Cdt Driss Al Harti",
      district: "Casablanca",
      address: "Bd Mohammed VI × Bd Commandant Driss Al Harti",
      location: { lat: 33.5425381, lng: -7.5825698 },
      mode: "adaptive",
      status: "watch",
      queueLength: 25,
      incidents: 0,
      averageDelaySeconds: 38,
      controllerId: "CTRL-0226",
      controllerConnectionState: "online",
      systemMode: "real",
      lastHeartbeat: "2026-04-27T08:29:40.000Z",
    },
    {
      id: "CAR-0188",
      name: "Carrefour Bd Oued Loukkous",
      district: "Casablanca",
      address: "Bd Oued Loukkous",
      location: { lat: 33.5581174, lng: -7.6802945 },
      mode: "adaptive",
      status: "healthy",
      queueLength: 14,
      incidents: 0,
      averageDelaySeconds: 24,
      controllerId: "CTRL-0188",
      controllerConnectionState: "online",
      systemMode: "real",
      lastHeartbeat: "2026-04-27T08:29:35.000Z",
    },
    {
      id: "CAR-0126",
      name: "Royal Mirage",
      district: "Fès",
      address: "Royal Mirage",
      location: { lat: 34.0375519, lng: -5.0056472 },
      mode: "adaptive",
      status: "healthy",
      queueLength: 12,
      incidents: 0,
      averageDelaySeconds: 22,
      controllerId: "CTRL-0126",
      controllerConnectionState: "online",
      systemMode: "real",
      lastHeartbeat: "2026-04-27T08:29:55.000Z",
    },
    {
      id: "CAR-0114",
      name: "National Rte 1 / Av Khalil Jabran",
      district: "El Jadida",
      address: "Route Nationale 1 × Avenue Khalil Jabran",
      location: { lat: 33.24430712763322, lng: -8.477469444274911 },
      mode: "fixed",
      status: "watch",
      queueLength: 9,
      incidents: 0,
      averageDelaySeconds: 19,
      controllerId: "CTRL-0114",
      controllerConnectionState: "degraded",
      systemMode: "real",
      lastHeartbeat: "2026-04-27T08:29:25.000Z",
    },
    {
      id: "CAR-0013",
      name: "Rue Al Manar / Av Attahrir / Rue 46",
      district: "El Jadida",
      address: "Rue Al Manar × Avenue Attahrir × Rue 46",
      location: { lat: 33.245188703493326, lng: -8.520399093254085 },
      mode: "adaptive",
      status: "healthy",
      queueLength: 7,
      incidents: 0,
      averageDelaySeconds: 16,
      controllerId: "CTRL-0013",
      controllerConnectionState: "online",
      systemMode: "real",
      lastHeartbeat: "2026-04-27T08:29:48.000Z",
    },
  ],
  corridors: [
    {
      id: "cor-tram-t3",
      label: "Tramway — Ligne T3",
      state: "pressure",
      volumeKph: 28,
      travelTimeMinutes: 9,
      path: [
        { lat: 33.5974227, lng: -7.6110049 },
        { lat: 33.576379, lng: -7.599331 },
      ],
    },
    {
      id: "cor-tram-t4",
      label: "Tramway — Ligne T4",
      state: "pressure",
      volumeKph: 24,
      travelTimeMinutes: 11,
      path: [
        { lat: 33.5874771, lng: -7.6158248 },
        { lat: 33.5974227, lng: -7.6110049 },
      ],
    },
    {
      id: "cor-bhns-l5",
      label: "BHNS — Ligne L5",
      state: "smooth",
      volumeKph: 32,
      travelTimeMinutes: 8,
      path: [
        { lat: 33.5425381, lng: -7.5825698 },
        { lat: 33.5581174, lng: -7.6802945 },
      ],
    },
  ],
  hardware: [
    {
      controllerId: "CTRL-0147",
      intersectionId: "CAR-0147",
      connectionState: "online",
      mode: "real",
      firmwareVersion: "CeRyX 4.2",
      uptimeHours: 1842,
      batteryBacked: true,
      lastSeen: "2026-04-27T08:29:45.000Z",
    },
    {
      controllerId: "CTRL-0169",
      intersectionId: "CAR-0169",
      connectionState: "online",
      mode: "real",
      firmwareVersion: "CeRyX 4.2",
      uptimeHours: 1620,
      batteryBacked: true,
      lastSeen: "2026-04-27T08:29:30.000Z",
    },
    {
      controllerId: "CTRL-0137",
      intersectionId: "CAR-0137",
      connectionState: "online",
      mode: "real",
      firmwareVersion: "CeRyX 4.2",
      uptimeHours: 1980,
      batteryBacked: true,
      lastSeen: "2026-04-27T08:29:50.000Z",
    },
    {
      controllerId: "CTRL-0226",
      intersectionId: "CAR-0226",
      connectionState: "online",
      mode: "real",
      firmwareVersion: "CeRyX 4.2",
      uptimeHours: 1410,
      batteryBacked: true,
      lastSeen: "2026-04-27T08:29:40.000Z",
    },
    {
      controllerId: "CTRL-0188",
      intersectionId: "CAR-0188",
      connectionState: "online",
      mode: "real",
      firmwareVersion: "CeRyX 4.2",
      uptimeHours: 1175,
      batteryBacked: true,
      lastSeen: "2026-04-27T08:29:35.000Z",
    },
    {
      controllerId: "CTRL-0126",
      intersectionId: "CAR-0126",
      connectionState: "online",
      mode: "real",
      firmwareVersion: "CeRyX 4.2",
      uptimeHours: 950,
      batteryBacked: true,
      lastSeen: "2026-04-27T08:29:55.000Z",
    },
    {
      controllerId: "CTRL-0114",
      intersectionId: "CAR-0114",
      connectionState: "degraded",
      mode: "real",
      firmwareVersion: "CeRyX 4.2",
      uptimeHours: 615,
      batteryBacked: true,
      lastSeen: "2026-04-27T08:29:25.000Z",
    },
    {
      controllerId: "CTRL-0013",
      intersectionId: "CAR-0013",
      connectionState: "online",
      mode: "real",
      firmwareVersion: "CeRyX 4.2",
      uptimeHours: 720,
      batteryBacked: true,
      lastSeen: "2026-04-27T08:29:48.000Z",
    },
  ],
  scenarios: [
    {
      id: "normal_traffic",
      label: "Normal traffic",
      description:
        "Plan HC/HM avec adaptatif et priorité tramway/BHNS standard.",
    },
    {
      id: "peak_traffic",
      label: "Peak traffic",
      description: "Plan HPM/HPS — cycles plus longs sur les axes Tram + L5/L6.",
    },
    {
      id: "emergency",
      label: "Emergency",
      description:
        "Priorité manuelle police / véhicule d'urgence, préemption transport collectif.",
    },
  ],
  alerts: [
    {
      id: "alert-001",
      level: "warning",
      title: "Pression cycle T3 — Bd Abbasside",
      detail:
        "Réserve de capacité réduite sur Bd MED 6 / Bd Abbasside (CAR-0147).",
      timestamp: "2026-04-27T08:25:00.000Z",
    },
    {
      id: "alert-002",
      level: "info",
      title: "Priorité bus BHNS L5 active",
      detail:
        "Fenêtres de priorité actives sur Mohammed VI / Cdt Driss Al Harti (CAR-0226).",
      timestamp: "2026-04-27T08:18:00.000Z",
    },
  ],
  systemState: "running",
};
